#!/usr/bin/env bash
set -euo pipefail

repo="${GH_REPO:-clement-tourriere/dbcrust}"
timeout_seconds=3600
skip_checks=0
skip_dry_run=0
increment=""

log() {
  printf '[dbcrust-release] %s\n' "$*" >&2
}

die() {
  printf '[dbcrust-release] ERROR: %s\n' "$*" >&2
  exit 1
}

usage() {
  cat <<'EOF'
Usage: bash .claude/skills/dbcrust-release/scripts/release.sh [options]

Cut and publish a DBCrust release:
  - verify the repository is clean and on main
  - run release checks (mise run check + commitizen dry-run)
  - run the Commitizen release bump (version files, CHANGELOG.md, signed tag)
  - push main and the release tag
  - wait for the GitHub Actions Release workflow (binaries, GitHub Release, PyPI)
  - print the final GitHub Release URL

Release notes are generated by the Release workflow from CHANGELOG.md;
this script does not edit them.

Options:
  --repo OWNER/REPO          GitHub repository. Default: clement-tourriere/dbcrust
  --timeout SECONDS          Wait timeout for workflow/release. Default: 3600
  --increment LEVEL          Force the bump level: patch, minor, or major.
                             Default: let Commitizen decide from the commits.
  --skip-checks              Skip all pre-release checks. Use only for recovery.
  --skip-dry-run             Run checks but skip the Commitizen bump dry-run.
  -h, --help                 Show this help.
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --repo)
      [ "$#" -ge 2 ] || die "--repo requires OWNER/REPO"
      repo="$2"
      shift 2
      ;;
    --timeout)
      [ "$#" -ge 2 ] || die "--timeout requires seconds"
      timeout_seconds="$2"
      shift 2
      ;;
    --increment)
      [ "$#" -ge 2 ] || die "--increment requires patch, minor, or major"
      increment="$2"
      case "$increment" in
        patch|minor|major) ;;
        *) die "--increment must be patch, minor, or major" ;;
      esac
      shift 2
      ;;
    --skip-checks)
      skip_checks=1
      shift
      ;;
    --skip-dry-run)
      skip_dry_run=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "Unknown option: $1"
      ;;
  esac
done

case "$timeout_seconds" in
  ''|*[!0-9]*) die "--timeout must be a positive integer" ;;
esac
[ "$timeout_seconds" -gt 0 ] || die "--timeout must be a positive integer"

run() {
  log "+ $*"
  "$@"
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || die "Missing required command: $1"
}

require_clean_tree() {
  if [ -n "$(git status --porcelain)" ]; then
    git status --short
    die "Working tree must be clean before releasing"
  fi
}

current_version() {
  awk -F'"' '/^version = / {print $2; exit}' Cargo.toml
}

latest_version_tag() {
  git tag --list 'v[0-9]*' --sort=-v:refname | head -n 1
}

wait_for_release_run() {
  local tag="$1"
  local tag_sha="$2"
  local deadline=$(( $(date +%s) + timeout_seconds ))
  local run_id=""

  log "Waiting for Release workflow for ${tag}..."
  while [ "$(date +%s)" -lt "$deadline" ]; do
    run_id="$(gh run list \
      --repo "$repo" \
      --workflow release.yml \
      --limit 30 \
      --json databaseId,headBranch,headSha,status,event \
      --jq ".[] | select((.headBranch == \"${tag}\") or (.headSha == \"${tag_sha}\" and .event == \"push\")) | .databaseId" \
      | head -n 1)"

    if [ -n "$run_id" ]; then
      log "Release workflow run: https://github.com/${repo}/actions/runs/${run_id}"
      if ! gh run watch "$run_id" --repo "$repo" --exit-status --interval 20; then
        die "Release workflow failed (tag is already pushed — rerun with 'gh run rerun ${run_id}' or fix and cut a patch release): https://github.com/${repo}/actions/runs/${run_id}"
      fi
      return 0
    fi

    sleep 10
  done

  die "Timed out waiting for Release workflow to start for ${tag}"
}

wait_for_github_release() {
  local tag="$1"
  local deadline=$(( $(date +%s) + timeout_seconds ))
  local url=""

  log "Waiting for GitHub Release ${tag}..."
  while [ "$(date +%s)" -lt "$deadline" ]; do
    url="$(gh release view "$tag" --repo "$repo" --json url --jq .url 2>/dev/null || true)"
    if [ -n "$url" ]; then
      printf '%s\n' "$url"
      return 0
    fi
    sleep 10
  done

  die "Timed out waiting for GitHub Release ${tag}"
}

require_command git
require_command gh
require_command mise

run gh auth status

if ! git rev-parse --show-toplevel >/dev/null 2>&1; then
  die "Not inside a Git repository"
fi
cd "$(git rev-parse --show-toplevel)"

[ -f mise.toml ] || die "mise.toml not found; run from the DBCrust repository"
[ -f .cz.toml ] || die ".cz.toml not found; run from the DBCrust repository"
[ -f .github/workflows/release.yml ] || die "Release workflow not found"

branch="$(git branch --show-current)"
[ "$branch" = "main" ] || die "Release must be run from main, current branch is '${branch:-detached}'"

require_clean_tree

run git fetch origin main --tags

local_sha="$(git rev-parse HEAD)"
remote_sha="$(git rev-parse origin/main)"
if [ "$local_sha" != "$remote_sha" ]; then
  if git merge-base --is-ancestor HEAD origin/main; then
    run git pull --ff-only origin main
  elif git merge-base --is-ancestor origin/main HEAD; then
    # Local main is ahead: unpushed commits about to be released. They get
    # pushed together with the bump commit and tag later in this script.
    log "Local main is ahead of origin/main; unpushed commits will ship with the release"
  else
    die "Local main and origin/main have diverged; reconcile before releasing"
  fi
fi

require_clean_tree

if [ "$skip_checks" -eq 0 ]; then
  run mise run check
  if [ "$skip_dry_run" -eq 0 ] && [ -z "$increment" ]; then
    # Dry-run only applies to the auto bump; a forced increment always bumps.
    log "+ mise run release:dry-run"
    set +e
    dry_output="$(mise run release:dry-run 2>&1)"
    dry_status=$?
    set -e
    printf '%s\n' "$dry_output" >&2
    if [ "$dry_status" -ne 0 ]; then
      # Commitizen exits 3 (no commits) or 21 (no bumpable commits) when
      # there is nothing to release.
      if [ "$dry_status" -eq 3 ] || [ "$dry_status" -eq 21 ] \
        || printf '%s' "$dry_output" | grep -qiE 'no commits|increment detected: *none'; then
        log "No release needed: no eligible conventional commits since the last tag."
        exit 0
      fi
      die "Commitizen dry-run failed (exit ${dry_status})"
    fi
  elif [ -n "$increment" ]; then
    log "Skipping bump dry-run because --increment ${increment} was provided"
  else
    log "Skipping bump dry-run because --skip-dry-run was provided"
  fi
  require_clean_tree
else
  log "Skipping pre-release checks because --skip-checks was provided"
fi

before_tag="$(latest_version_tag || true)"
log "Latest tag before bump: ${before_tag:-<none>}"

# The bump creates a GPG-signed commit and tag (gpg_sign = true in .cz.toml)
# and runs the pre-bump hooks (cargo check, hk run fix).
if [ -n "$increment" ]; then
  run mise run "release:${increment}"
else
  run mise run release
fi

version="$(current_version)"
[ -n "$version" ] || die "Could not read version from Cargo.toml"
tag="v${version}"

if ! git rev-parse -q --verify "refs/tags/${tag}" >/dev/null; then
  die "Expected release tag ${tag} was not created"
fi

tag_sha="$(git rev-list -n 1 "$tag")"
head_sha="$(git rev-parse HEAD)"
if [ "$tag_sha" != "$head_sha" ]; then
  log "No release needed: ${tag} does not point at HEAD."
  log "Tag ${tag}: ${tag_sha}"
  log "HEAD: ${head_sha}"
  exit 0
fi

if [ -n "$(git status --porcelain)" ]; then
  git status --short
  die "Working tree is dirty after the bump (pre-bump hooks left changes). The bump commit and tag ${tag} exist locally but were NOT pushed. Inspect the changes, then push manually: git push origin main && git push origin ${tag}"
fi

log "Release tag: ${tag} (${tag_sha})"
log "Previous tag: ${before_tag:-<none>}"

run git push origin main
run git push origin "$tag"

wait_for_release_run "$tag" "$tag_sha"
release_url="$(wait_for_github_release "$tag")"

log "Release complete: ${release_url}"
log "PyPI publish and binary uploads are handled by the Release workflow (watched above)."
