[tool.commitizen]
name = "cz_conventional_commits"
version = "0.3.0"
tag_format = "v$version"
version_scheme = "semver"
update_changelog_on_bump = true
bump_message = "release: v$current_version → v$new_version"

# Handle existing tags without 'v' prefix
legacy_tag_formats = [
    "$version"
]

# Files to update with new version
version_files = [
    "Cargo.toml:version",
    "pyproject.toml:version"
]

# Pre-bump hooks to ensure everything is ready
pre_bump_hooks = [
    "cargo test",
    "cargo build --release",
    "maturin build --release"
]

# Changelog settings
changelog_file = "CHANGELOG.md"
changelog_incremental = true
changelog_start_rev = "0.0.1"