[tool.commitizen]
name = "cz_conventional_commits"
version = "0.2.4"
tag_format = "v$version"
version_scheme = "semver"
#update_changelog_on_bump = true
bump_message = "release: v$current_version → v$new_version"
gpg_sign = true


# Files to update with new version
version_files = [
    "Cargo.toml:version",
    "pyproject.toml:version",
    "Cargo.lock:version"
]

# Post-bump hooks to update Cargo.lock
post_bump_hooks = [
    "cargo check"
]


# Changelog settings
changelog_file = "CHANGELOG.md"
#changelog_incremental = true
#changelog_start_rev = "0.0.1"