[tool.commitizen]
name = "cz_conventional_commits"
version = "0.21.4"
tag_format = "v$version"
version_scheme = "semver"
update_changelog_on_bump = true
bump_message = "release: v$current_version → v$new_version"
gpg_sign = true


# Files to update with new version
version_files = [
    "Cargo.toml:version",
    "pyproject.toml:version"
]

# Pre-bump hooks to update Cargo.lock and run pre-commit before commit
pre_bump_hooks = [
    "cargo check", # Update Cargo.lock
    "pre-commit run", # Fix before tagging
]


# Changelog settings
changelog_file = "CHANGELOG.md"
#changelog_incremental = true
#changelog_start_rev = "0.0.1"
