export interface QueryPreset {
  name: string;
  label: string;
  description: string;
  query: string;
  requiredTables: string[];
}

export interface QueryPresetGroup {
  id: string;
  title: string;
  description: string;
  presets: QueryPreset[];
}

const DJANGO_PRESET_GROUPS: QueryPresetGroup[] = [
  {
    id: "models",
    title: "Models & Content Types",
    description: "Browse Django apps, models, and the permission surface tied to them.",
    presets: [
      {
        name: "django_content_types_catalog",
        label: "Content type catalog",
        description: "List Django apps and models registered in content types.",
        query: `SELECT app_label, model
FROM django_content_type
ORDER BY app_label, model;`,
        requiredTables: ["django_content_type"],
      },
      {
        name: "django_model_inventory",
        label: "Model inventory",
        description: "Count models per Django app from content types.",
        query: `SELECT app_label, COUNT(*) AS model_count
FROM django_content_type
GROUP BY app_label
ORDER BY app_label;`,
        requiredTables: ["django_content_type"],
      },
      {
        name: "django_model_permission_matrix",
        label: "Model permission matrix",
        description: "Inspect model-level permissions generated by Django.",
        query: `SELECT c.app_label,
       c.model,
       p.codename,
       p.name
FROM auth_permission AS p
JOIN django_content_type AS c ON c.id = p.content_type_id
ORDER BY c.app_label, c.model, p.codename;`,
        requiredTables: ["django_content_type", "auth_permission"],
      },
    ],
  },
  {
    id: "migrations",
    title: "Migration Health",
    description: "Summarize migration activity and spot apps with uneven rollout history.",
    presets: [
      {
        name: "django_recent_migrations",
        label: "Recent migrations",
        description: "Show the latest applied migrations across apps.",
        query: `SELECT app, name, applied
FROM django_migrations
ORDER BY applied DESC
LIMIT 50;`,
        requiredTables: ["django_migrations"],
      },
      {
        name: "django_migration_health_summary",
        label: "Migration summary",
        description: "Count applied migrations and show the last applied time per app.",
        query: `SELECT app,
       COUNT(*) AS applied_migrations,
       MIN(applied) AS first_applied,
       MAX(applied) AS last_applied
FROM django_migrations
GROUP BY app
ORDER BY app;`,
        requiredTables: ["django_migrations"],
      },
      {
        name: "django_migration_name_frequency",
        label: "Migration name frequency",
        description: "Surface repeated migration names across apps to inspect conventions and rollout patterns.",
        query: `SELECT name,
       COUNT(*) AS app_count,
       MIN(app) AS first_app,
       MAX(app) AS last_app
FROM django_migrations
GROUP BY name
HAVING COUNT(*) > 1
ORDER BY app_count DESC, name;`,
        requiredTables: ["django_migrations"],
      },
    ],
  },
  {
    id: "auth",
    title: "Auth & Permissions",
    description: "Inspect Django auth users, groups, and direct permission assignments.",
    presets: [
      {
        name: "django_auth_users_overview",
        label: "Auth users",
        description: "Review built-in auth users and login state.",
        query: `SELECT id,
       username,
       email,
       is_staff,
       is_superuser,
       is_active,
       last_login,
       date_joined
FROM auth_user
ORDER BY id DESC
LIMIT 100;`,
        requiredTables: ["auth_user"],
      },
      {
        name: "django_group_permission_counts",
        label: "Group permission counts",
        description: "Count permissions granted to each Django auth group.",
        query: `SELECT g.name AS group_name,
       COUNT(gp.permission_id) AS permission_count
FROM auth_group AS g
LEFT JOIN auth_group_permissions AS gp ON gp.group_id = g.id
GROUP BY g.id, g.name
ORDER BY g.name;`,
        requiredTables: ["auth_group", "auth_group_permissions"],
      },
      {
        name: "django_group_permissions_detail",
        label: "Group permission detail",
        description: "Show which content-type permissions each group owns.",
        query: `SELECT g.name AS group_name,
       c.app_label,
       c.model,
       p.codename
FROM auth_group AS g
JOIN auth_group_permissions AS gp ON gp.group_id = g.id
JOIN auth_permission AS p ON p.id = gp.permission_id
JOIN django_content_type AS c ON c.id = p.content_type_id
ORDER BY g.name, c.app_label, c.model, p.codename;`,
        requiredTables: [
          "auth_group",
          "auth_group_permissions",
          "auth_permission",
          "django_content_type",
        ],
      },
      {
        name: "django_user_group_membership",
        label: "User group membership",
        description: "Map auth users to the groups they belong to.",
        query: `SELECT u.username,
       g.name AS group_name
FROM auth_user AS u
JOIN auth_user_groups AS ug ON ug.user_id = u.id
JOIN auth_group AS g ON g.id = ug.group_id
ORDER BY u.username, g.name;`,
        requiredTables: ["auth_user", "auth_user_groups", "auth_group"],
      },
      {
        name: "django_direct_user_permissions",
        label: "Direct user permissions",
        description: "Inspect permissions granted directly to users outside group membership.",
        query: `SELECT u.username,
       c.app_label,
       c.model,
       p.codename
FROM auth_user AS u
JOIN auth_user_user_permissions AS up ON up.user_id = u.id
JOIN auth_permission AS p ON p.id = up.permission_id
JOIN django_content_type AS c ON c.id = p.content_type_id
ORDER BY u.username, c.app_label, c.model, p.codename;`,
        requiredTables: [
          "auth_user",
          "auth_user_user_permissions",
          "auth_permission",
          "django_content_type",
        ],
      },
    ],
  },
  {
    id: "sessions",
    title: "Sessions & Activity",
    description: "Monitor active sessions, admin activity logs, and site configuration.",
    presets: [
      {
        name: "django_active_sessions",
        label: "Active sessions",
        description: "List stored sessions with expiry dates. Helps spot stale sessions.",
        query: `SELECT session_key,
       expire_date,
       CASE WHEN expire_date > CURRENT_TIMESTAMP THEN 'active' ELSE 'expired' END AS status
FROM django_session
ORDER BY expire_date DESC
LIMIT 100;`,
        requiredTables: ["django_session"],
      },
      {
        name: "django_session_stats",
        label: "Session statistics",
        description: "Count active vs expired sessions to gauge cleanup health.",
        query: `SELECT
  COUNT(*) AS total_sessions,
  SUM(CASE WHEN expire_date > CURRENT_TIMESTAMP THEN 1 ELSE 0 END) AS active,
  SUM(CASE WHEN expire_date <= CURRENT_TIMESTAMP THEN 1 ELSE 0 END) AS expired
FROM django_session;`,
        requiredTables: ["django_session"],
      },
      {
        name: "django_admin_log_recent",
        label: "Recent admin actions",
        description: "Audit trail of the latest admin panel actions.",
        query: `SELECT l.action_time,
       u.username,
       c.app_label || '.' || c.model AS object_type,
       l.object_repr,
       CASE l.action_flag
         WHEN 1 THEN 'Add'
         WHEN 2 THEN 'Change'
         WHEN 3 THEN 'Delete'
       END AS action,
       l.change_message
FROM django_admin_log AS l
JOIN auth_user AS u ON u.id = l.user_id
LEFT JOIN django_content_type AS c ON c.id = l.content_type_id
ORDER BY l.action_time DESC
LIMIT 50;`,
        requiredTables: ["django_admin_log", "auth_user", "django_content_type"],
      },
      {
        name: "django_admin_log_by_user",
        label: "Admin actions per user",
        description: "Count admin actions grouped by user to see who is most active.",
        query: `SELECT u.username,
       COUNT(*) AS total_actions,
       SUM(CASE WHEN l.action_flag = 1 THEN 1 ELSE 0 END) AS adds,
       SUM(CASE WHEN l.action_flag = 2 THEN 1 ELSE 0 END) AS changes,
       SUM(CASE WHEN l.action_flag = 3 THEN 1 ELSE 0 END) AS deletes,
       MAX(l.action_time) AS last_action
FROM django_admin_log AS l
JOIN auth_user AS u ON u.id = l.user_id
GROUP BY u.username
ORDER BY total_actions DESC;`,
        requiredTables: ["django_admin_log", "auth_user"],
      },
      {
        name: "django_sites",
        label: "Sites configuration",
        description: "View Django sites framework entries (domain and name).",
        query: `SELECT id, domain, name
FROM django_site
ORDER BY id;`,
        requiredTables: ["django_site"],
      },
    ],
  },
  {
    id: "diagnostics",
    title: "Project Diagnostics",
    description: "Detect stale data, orphaned records, and framework health indicators.",
    presets: [
      {
        name: "django_stale_content_types",
        label: "Stale content types",
        description: "Find content types with zero permissions — may indicate removed models.",
        query: `SELECT c.app_label,
       c.model,
       c.id AS content_type_id
FROM django_content_type AS c
LEFT JOIN auth_permission AS p ON p.content_type_id = c.id
WHERE p.id IS NULL
ORDER BY c.app_label, c.model;`,
        requiredTables: ["django_content_type", "auth_permission"],
      },
      {
        name: "django_superusers",
        label: "Superuser audit",
        description: "List all superusers — review for security compliance.",
        query: `SELECT id, username, email, is_active, last_login, date_joined
FROM auth_user
WHERE is_superuser = 1
ORDER BY date_joined;`,
        requiredTables: ["auth_user"],
      },
      {
        name: "django_inactive_staff",
        label: "Inactive staff accounts",
        description: "Find staff users that are deactivated — potential cleanup targets.",
        query: `SELECT id, username, email, last_login, date_joined
FROM auth_user
WHERE is_staff = 1 AND is_active = 0
ORDER BY last_login DESC;`,
        requiredTables: ["auth_user"],
      },
      {
        name: "django_users_never_logged_in",
        label: "Users never logged in",
        description: "Find user accounts that were created but never used.",
        query: `SELECT id, username, email, date_joined
FROM auth_user
WHERE last_login IS NULL
ORDER BY date_joined DESC;`,
        requiredTables: ["auth_user"],
      },
      {
        name: "django_table_row_counts",
        label: "Django table sizes",
        description: "Quick row count for all core Django tables to assess database size.",
        query: `SELECT 'auth_user' AS table_name, COUNT(*) AS row_count FROM auth_user
UNION ALL SELECT 'auth_group', COUNT(*) FROM auth_group
UNION ALL SELECT 'auth_permission', COUNT(*) FROM auth_permission
UNION ALL SELECT 'django_content_type', COUNT(*) FROM django_content_type
UNION ALL SELECT 'django_migrations', COUNT(*) FROM django_migrations
ORDER BY row_count DESC;`,
        requiredTables: ["auth_user", "auth_group", "auth_permission", "django_content_type", "django_migrations"],
      },
    ],
  },
];

export function getVisibleDjangoPresetGroups(
  tables: string[],
): QueryPresetGroup[] {
  const tableSet = new Set(tables);

  return DJANGO_PRESET_GROUPS.map((group) => ({
    ...group,
    presets: group.presets.filter((preset) =>
      preset.requiredTables.every((table) => tableSet.has(table)),
    ),
  })).filter((group) => group.presets.length > 0);
}

export function getVisibleDjangoPresets(tables: string[]): QueryPreset[] {
  return getVisibleDjangoPresetGroups(tables).flatMap((group) => group.presets);
}
