export interface QueryPreset {
  name: string;
  label: string;
  description: string;
  query: string;
  requiredTables: string[];
}

export interface QueryPresetGroup {
  id: string;
  title: string;
  description: string;
  presets: QueryPreset[];
}

const DJANGO_PRESET_GROUPS: QueryPresetGroup[] = [
  {
    id: "models",
    title: "Models & Content Types",
    description: "Browse Django apps, models, and the permission surface tied to them.",
    presets: [
      {
        name: "django_content_types_catalog",
        label: "Content type catalog",
        description: "List Django apps and models registered in content types.",
        query: `SELECT app_label, model
FROM django_content_type
ORDER BY app_label, model;`,
        requiredTables: ["django_content_type"],
      },
      {
        name: "django_model_inventory",
        label: "Model inventory",
        description: "Count models per Django app from content types.",
        query: `SELECT app_label, COUNT(*) AS model_count
FROM django_content_type
GROUP BY app_label
ORDER BY app_label;`,
        requiredTables: ["django_content_type"],
      },
      {
        name: "django_model_permission_matrix",
        label: "Model permission matrix",
        description: "Inspect model-level permissions generated by Django.",
        query: `SELECT c.app_label,
       c.model,
       p.codename,
       p.name
FROM auth_permission AS p
JOIN django_content_type AS c ON c.id = p.content_type_id
ORDER BY c.app_label, c.model, p.codename;`,
        requiredTables: ["django_content_type", "auth_permission"],
      },
    ],
  },
  {
    id: "migrations",
    title: "Migration Health",
    description: "Summarize migration activity and spot apps with uneven rollout history.",
    presets: [
      {
        name: "django_recent_migrations",
        label: "Recent migrations",
        description: "Show the latest applied migrations across apps.",
        query: `SELECT app, name, applied
FROM django_migrations
ORDER BY applied DESC
LIMIT 50;`,
        requiredTables: ["django_migrations"],
      },
      {
        name: "django_migration_health_summary",
        label: "Migration summary",
        description: "Count applied migrations and show the last applied time per app.",
        query: `SELECT app,
       COUNT(*) AS applied_migrations,
       MIN(applied) AS first_applied,
       MAX(applied) AS last_applied
FROM django_migrations
GROUP BY app
ORDER BY app;`,
        requiredTables: ["django_migrations"],
      },
      {
        name: "django_migration_name_frequency",
        label: "Migration name frequency",
        description: "Surface repeated migration names across apps to inspect conventions and rollout patterns.",
        query: `SELECT name,
       COUNT(*) AS app_count,
       MIN(app) AS first_app,
       MAX(app) AS last_app
FROM django_migrations
GROUP BY name
HAVING COUNT(*) > 1
ORDER BY app_count DESC, name;`,
        requiredTables: ["django_migrations"],
      },
    ],
  },
  {
    id: "auth",
    title: "Auth & Permissions",
    description: "Inspect Django auth users, groups, and direct permission assignments.",
    presets: [
      {
        name: "django_auth_users_overview",
        label: "Auth users",
        description: "Review built-in auth users and login state.",
        query: `SELECT id,
       username,
       email,
       is_staff,
       is_superuser,
       is_active,
       last_login,
       date_joined
FROM auth_user
ORDER BY id DESC
LIMIT 100;`,
        requiredTables: ["auth_user"],
      },
      {
        name: "django_group_permission_counts",
        label: "Group permission counts",
        description: "Count permissions granted to each Django auth group.",
        query: `SELECT g.name AS group_name,
       COUNT(gp.permission_id) AS permission_count
FROM auth_group AS g
LEFT JOIN auth_group_permissions AS gp ON gp.group_id = g.id
GROUP BY g.id, g.name
ORDER BY g.name;`,
        requiredTables: ["auth_group", "auth_group_permissions"],
      },
      {
        name: "django_group_permissions_detail",
        label: "Group permission detail",
        description: "Show which content-type permissions each group owns.",
        query: `SELECT g.name AS group_name,
       c.app_label,
       c.model,
       p.codename
FROM auth_group AS g
JOIN auth_group_permissions AS gp ON gp.group_id = g.id
JOIN auth_permission AS p ON p.id = gp.permission_id
JOIN django_content_type AS c ON c.id = p.content_type_id
ORDER BY g.name, c.app_label, c.model, p.codename;`,
        requiredTables: [
          "auth_group",
          "auth_group_permissions",
          "auth_permission",
          "django_content_type",
        ],
      },
      {
        name: "django_user_group_membership",
        label: "User group membership",
        description: "Map auth users to the groups they belong to.",
        query: `SELECT u.username,
       g.name AS group_name
FROM auth_user AS u
JOIN auth_user_groups AS ug ON ug.user_id = u.id
JOIN auth_group AS g ON g.id = ug.group_id
ORDER BY u.username, g.name;`,
        requiredTables: ["auth_user", "auth_user_groups", "auth_group"],
      },
      {
        name: "django_direct_user_permissions",
        label: "Direct user permissions",
        description: "Inspect permissions granted directly to users outside group membership.",
        query: `SELECT u.username,
       c.app_label,
       c.model,
       p.codename
FROM auth_user AS u
JOIN auth_user_user_permissions AS up ON up.user_id = u.id
JOIN auth_permission AS p ON p.id = up.permission_id
JOIN django_content_type AS c ON c.id = p.content_type_id
ORDER BY u.username, c.app_label, c.model, p.codename;`,
        requiredTables: [
          "auth_user",
          "auth_user_user_permissions",
          "auth_permission",
          "django_content_type",
        ],
      },
    ],
  },
];

export function getVisibleDjangoPresetGroups(
  tables: string[],
): QueryPresetGroup[] {
  const tableSet = new Set(tables);

  return DJANGO_PRESET_GROUPS.map((group) => ({
    ...group,
    presets: group.presets.filter((preset) =>
      preset.requiredTables.every((table) => tableSet.has(table)),
    ),
  })).filter((group) => group.presets.length > 0);
}

export function getVisibleDjangoPresets(tables: string[]): QueryPreset[] {
  return getVisibleDjangoPresetGroups(tables).flatMap((group) => group.presets);
}
