const SQL_RESERVED_WORDS = new Set([
  "ALL",
  "ALTER",
  "AND",
  "AS",
  "ASC",
  "BETWEEN",
  "BY",
  "CASE",
  "CREATE",
  "CROSS",
  "DELETE",
  "DESC",
  "DISTINCT",
  "DROP",
  "ELSE",
  "END",
  "EXISTS",
  "FALSE",
  "FROM",
  "FULL",
  "GROUP",
  "HAVING",
  "IN",
  "INNER",
  "INSERT",
  "INTERSECT",
  "INTO",
  "IS",
  "JOIN",
  "LEFT",
  "LIKE",
  "LIMIT",
  "MATCH",
  "NOT",
  "NULL",
  "OFFSET",
  "ON",
  "OR",
  "ORDER",
  "OUTER",
  "PRIMARY",
  "QUERY",
  "REFERENCES",
  "RIGHT",
  "SELECT",
  "SET",
  "TABLE",
  "THEN",
  "TRUE",
  "UNION",
  "UNIQUE",
  "UPDATE",
  "VALUES",
  "VIEW",
  "WHEN",
  "WHERE",
  "WITH",
]);

function isQuotedIdentifier(identifier: string): boolean {
  return (
    (identifier.startsWith('"') && identifier.endsWith('"')) ||
    (identifier.startsWith("`") && identifier.endsWith("`")) ||
    (identifier.startsWith("[") && identifier.endsWith("]"))
  );
}

/** Strip one pair of surrounding identifier quotes, unescaping doubled quotes. */
export function unquoteIdentifier(identifier: string): string {
  const trimmed = identifier.trim();
  if (trimmed.length >= 2) {
    if (trimmed.startsWith('"') && trimmed.endsWith('"')) {
      return trimmed.slice(1, -1).replace(/""/g, '"');
    }
    if (trimmed.startsWith("`") && trimmed.endsWith("`")) {
      return trimmed.slice(1, -1).replace(/``/g, "`");
    }
    if (trimmed.startsWith("[") && trimmed.endsWith("]")) {
      return trimmed.slice(1, -1);
    }
  }
  return trimmed;
}

/**
 * Split a possibly-quoted qualified name on dots that sit outside quotes,
 * keeping each part's quoting (`analytics."v1.events"` → [analytics, "v1.events"]).
 */
export function splitQualifiedIdentifier(name: string): string[] {
  const parts: string[] = [];
  let current = "";
  let quote: string | null = null;
  for (let index = 0; index < name.length; index++) {
    const character = name[index];
    if (quote) {
      current += character;
      if (character === quote) {
        if (quote !== "]" && name[index + 1] === quote) {
          current += name[index + 1];
          index++;
        } else {
          quote = null;
        }
      }
    } else if (character === '"' || character === "`") {
      quote = character;
      current += character;
    } else if (character === "[") {
      quote = "]";
      current += character;
    } else if (character === ".") {
      parts.push(current);
      current = "";
    } else {
      current += character;
    }
  }
  parts.push(current);
  return parts;
}

function identifierQuotes(databaseType?: string): [string, string] {
  return databaseType === "MySQL" || databaseType === "ClickHouse"
    ? ["`", "`"]
    : ['"', '"'];
}

/** Format one database identifier for SQL generated by the GUI. */
export function formatIdentifier(
  identifier: string,
  databaseType?: string,
): string {
  const trimmed = identifier.trim();
  if (!trimmed || isQuotedIdentifier(trimmed)) return trimmed;

  const validPattern =
    databaseType === "PostgreSQL"
      ? /^[a-z_][a-z0-9_$]*$/
      : /^[A-Za-z_][A-Za-z0-9_$]*$/;
  if (validPattern.test(trimmed) && !SQL_RESERVED_WORDS.has(trimmed.toUpperCase())) {
    return trimmed;
  }

  const [open, close] = identifierQuotes(databaseType);
  return `${open}${trimmed.split(close).join(close + close)}${close}`;
}

const DATAFUSION_TYPES = new Set(["Parquet", "CSV", "JSON", "DuckDB"]);

/** A dotted name is a struct path only when its head segment is itself a column. */
function dottedHeadIsColumn(
  name: string,
  tableColumns?: readonly string[],
): boolean {
  const dot = name.indexOf(".");
  if (dot <= 0 || !tableColumns) return false;
  const head = name.slice(0, dot);
  return tableColumns.includes(head);
}

/** Format a backend object name for use in a query generated by the GUI. */
export function formatColumnReference(
  columnName: string,
  databaseType?: string,
  tableColumns?: readonly string[],
): string {
  // Elasticsearch/MongoDB dots are always path traversal. For DataFusion
  // backends they are struct access only when the head segment is a column —
  // a flat column literally named `price.usd` must be quoted whole, since
  // "price"."usd" resolves as relation.column.
  const splitDotted =
    databaseType === "Elasticsearch" ||
    databaseType === "MongoDB" ||
    (DATAFUSION_TYPES.has(databaseType ?? "") &&
      dottedHeadIsColumn(columnName, tableColumns));
  if (splitDotted && columnName.includes(".")) {
    return columnName
      .split(".")
      .map((part) => formatIdentifier(part, databaseType))
      .join(".");
  }
  return formatIdentifier(columnName, databaseType);
}

export function formatTableReference(
  tableName: string,
  databaseType?: string,
): string {
  const trimmed = tableName.trim();
  if (!trimmed || isQuotedIdentifier(trimmed)) return trimmed;

  // PostgreSQL metadata qualifies non-public objects as `schema.table`
  // (quoting parts that contain dots). Other providers list objects from the
  // active database/schema, so a dot is part of the object name and the whole
  // identifier must be quoted.
  if (databaseType === "PostgreSQL") {
    return splitQualifiedIdentifier(trimmed)
      .map((part) =>
        isQuotedIdentifier(part) ? part : formatIdentifier(part, databaseType),
      )
      .join(".");
  }

  return formatIdentifier(trimmed, databaseType);
}

export function isSystemTableName(
  tableName: string,
  databaseType?: string,
): boolean {
  const normalized = tableName.trim().toLowerCase();

  if (!normalized) return false;

  switch (databaseType) {
    case "PostgreSQL":
      return (
        normalized.startsWith("pg_") ||
        normalized.startsWith("information_schema") ||
        normalized.startsWith("pg_toast")
      );
    case "MySQL":
      return (
        normalized.startsWith("information_schema") ||
        normalized.startsWith("performance_schema") ||
        normalized === "mysql" ||
        normalized.startsWith("mysql.") ||
        normalized === "sys" ||
        normalized.startsWith("sys.")
      );
    case "SQLite":
      return normalized.startsWith("sqlite_");
    case "ClickHouse":
      return normalized === "system" || normalized.startsWith("system.");
    case "MongoDB":
      return normalized.startsWith("system.");
    case "Elasticsearch":
      return normalized.startsWith(".");
    case "DuckDB":
      return normalized.startsWith("duckdb_") || normalized.startsWith("sqlite_");
    default:
      return (
        normalized.startsWith("pg_") ||
        normalized.startsWith("information_schema") ||
        normalized.startsWith("sqlite_") ||
        normalized.startsWith("system.")
      );
  }
}

export function sortTablesForUi(
  tables: readonly string[],
  databaseType?: string,
): string[] {
  return Array.from(new Set(tables.filter(Boolean))).sort((left, right) => {
    const leftSystem = isSystemTableName(left, databaseType) ? 1 : 0;
    const rightSystem = isSystemTableName(right, databaseType) ? 1 : 0;

    if (leftSystem !== rightSystem) {
      return leftSystem - rightSystem;
    }

    return left.localeCompare(right, undefined, {
      numeric: true,
      sensitivity: "base",
    });
  });
}

/**
 * Quote a packed-name part when a literal dot or quote inside it would make
 * the joined `schema.table` string ambiguous (mirrors the Rust pack site).
 */
function packQualifiedPart(part: string): string {
  return part.includes(".") || part.includes('"')
    ? `"${part.replace(/"/g, '""')}"`
    : part;
}

export function extractTableNames(
  rows: readonly (string | null)[][],
  databaseType?: string,
): string[] {
  return sortTablesForUi(
    rows
      .map((row) => {
        const schema = row[0]?.trim();
        const tableName = row[1]?.trim();
        if (!tableName) return null;
        if (databaseType !== "PostgreSQL") return tableName;
        return schema && schema !== "public"
          ? `${packQualifiedPart(schema)}.${packQualifiedPart(tableName)}`
          : packQualifiedPart(tableName);
      })
      .filter((tableName): tableName is string => Boolean(tableName)),
    databaseType,
  );
}
