//! Shell completion for the connection URL positional.
//!
//! The completion scripts `--completions` prints are generated by `usage`;
//! at Tab time they call `dbcrust __complete_word__ …` and this module answers
//! for the `URL` argument: scheme prefixes, saved sessions, Docker database
//! containers, and compatible local files. Flags, subcommands, and value
//! enums come from the CLI grammar itself.

use std::ffi::OsStr;
use std::path::Path;

use strum::IntoEnumIterator;
use usage::complete::{Candidate, CompleteCtx, Shell};
use usage::spec::CommandArgs;

use crate::cli::Args;
use crate::database::DatabaseTypeExt;
use crate::url_scheme::UrlScheme;

/// Completer for `Args::connection_url`, invoked by the generated grammar.
pub fn complete_connection_url(
    _partial: &<Args as CommandArgs>::Partial,
    ctx: &CompleteCtx<'_>,
) -> Vec<Candidate<'static>> {
    url_candidates(ctx.prefix)
}

/// Candidates for a partially typed connection URL.
///
/// Everything is answered from here rather than filtered: the caller keeps
/// only candidates starting with `prefix`, so a scheme list is cheap to
/// offer in full, and expensive lookups (`docker ps`, directory listings)
/// only run once the prefix says which one is wanted.
pub fn url_candidates(prefix: &str) -> Vec<Candidate<'static>> {
    let Some((scheme, rest)) = prefix.split_once("://") else {
        let mut candidates = scheme_candidates();
        candidates.extend(path_candidates("", prefix));
        return candidates;
    };
    match scheme {
        "session" => session_candidates(),
        "docker" if !rest.contains('/') => docker_container_candidates(),
        "sqlite" | "duckdb" | "parquet" | "csv" | "json" | "ndjson" => {
            path_candidates(&format!("{scheme}://"), rest)
        }
        _ => Vec::new(),
    }
}

/// Every `scheme://` prefix, described.
pub fn scheme_candidates() -> Vec<Candidate<'static>> {
    UrlScheme::iter()
        .map(|scheme| Candidate::described(scheme.url_prefix(), scheme.description()))
        .collect()
}

/// `session://NAME` for each saved session.
fn session_candidates() -> Vec<Candidate<'static>> {
    let config = crate::config::Config::load();
    let mut sessions = config.list_sessions();
    sessions.sort_by(|(a, _), (b, _)| a.cmp(b));
    sessions
        .into_iter()
        .map(|(name, session)| {
            let description = if session.database_type.is_file_based() {
                session.file_path.unwrap_or_default()
            } else {
                format!(
                    "{}@{}:{}/{}",
                    session.user, session.host, session.port, session.dbname
                )
            };
            Candidate::described(format!("session://{name}"), description)
        })
        .collect()
}

/// `docker://NAME` for each running container whose image looks like a
/// database (the same heuristic the previous shell-side scripts used).
fn docker_container_candidates() -> Vec<Candidate<'static>> {
    let output = std::process::Command::new("docker")
        .args(["ps", "--format", "{{.Names}}\t{{.Image}}"])
        .output();
    let Ok(output) = output else {
        return Vec::new();
    };
    if !output.status.success() {
        return Vec::new();
    }
    String::from_utf8_lossy(&output.stdout)
        .lines()
        .filter_map(|line| {
            let (name, image) = line.split_once('\t')?;
            let image_lower = image.to_ascii_lowercase();
            [
                "postgres",
                "mysql",
                "mariadb",
                "sqlite",
                "clickhouse",
                "mongo",
                "elastic",
            ]
            .iter()
            .any(|needle| image_lower.contains(needle))
            .then(|| Candidate::described(format!("docker://{name}"), image.to_string()))
        })
        .collect()
}

/// Filesystem candidates for `typed`, each prefixed with `url_prefix`:
/// directories (with a trailing `/`, so the next Tab descends) and files
/// DBCrust can open by extension.
fn path_candidates(url_prefix: &str, typed: &str) -> Vec<Candidate<'static>> {
    // A flag-looking word is not a path, and `-` alone is ambiguous
    if typed.starts_with('-') {
        return Vec::new();
    }
    let (dir_part, _) = typed.rsplit_once('/').unwrap_or(("", typed));
    let dir = if typed.ends_with('/') {
        typed.to_string()
    } else if dir_part.is_empty() && !typed.starts_with('/') {
        String::new()
    } else {
        format!("{dir_part}/")
    };
    let read_dir = if dir.is_empty() {
        Path::new(".").read_dir()
    } else {
        Path::new(&dir).read_dir()
    };
    let Ok(entries) = read_dir else {
        return Vec::new();
    };

    let mut candidates: Vec<Candidate<'static>> = entries
        .filter_map(Result::ok)
        .filter_map(|entry| {
            let name = entry.file_name();
            let name = name.to_str()?;
            if name.starts_with('.') && !typed.rsplit('/').next().unwrap_or("").starts_with('.') {
                return None;
            }
            let path = entry.path();
            if path.is_dir() {
                return Some(Candidate::new(format!("{url_prefix}{dir}{name}/")));
            }
            let (database_type, _) = crate::cli_core::CliCore::detect_file_database_type(name)?;
            Some(Candidate::described(
                format!("{url_prefix}{dir}{name}"),
                database_type.to_string(),
            ))
        })
        .collect();
    candidates.sort();
    candidates
}

/// The completion script for `shell`, targeting `binary_name` (`dbcrust` or
/// the `dbc` alias — the script calls that name back at completion time).
pub fn completion_script(shell: Shell, binary_name: &str) -> String {
    let script = Args::completion_script(shell, binary_name);
    match shell {
        Shell::Bash => patch_bash_colon_words(&script),
        _ => script,
    }
}

/// bash splits words at `:` (`COMP_WORDBREAKS`), so a reply of
/// `session://prod` for the word `session://p` would be inserted after the
/// `session:` already on the line. Trim the part up to the last colon from
/// every reply, the way bash-completion's `__ltrim_colon_completions` does.
fn patch_bash_colon_words(script: &str) -> String {
    const ANCHOR: &str = "    done <<< \"$__usage_out\"\n";
    const FIX: &str = r#"
    if [[ $COMP_WORDBREAKS == *:* ]]; then
        local __usage_word="${COMP_LINE:0:$COMP_POINT}"
        __usage_word="${__usage_word##* }"
        if [[ $__usage_word == *:* ]]; then
            local __usage_colon_prefix="${__usage_word%:*}:" __usage_i
            for __usage_i in "${!COMPREPLY[@]}"; do
                COMPREPLY[__usage_i]="${COMPREPLY[__usage_i]#"$__usage_colon_prefix"}"
            done
        fi
    fi
"#;
    match script.find(ANCHOR) {
        Some(at) => {
            let split = at + ANCHOR.len();
            format!("{}{}{}", &script[..split], FIX, &script[split..])
        }
        None => {
            tracing::warn!("usage bash completion script changed shape; colon fix not applied");
            script.to_string()
        }
    }
}

/// The binary name a script should call back, from argv0 (`dbc` for the
/// alias binary and entry point; `dbcrust` when unknown).
pub fn binary_name_from_argv0(argv0: Option<&OsStr>) -> String {
    argv0
        .and_then(|arg| Path::new(arg).file_name())
        .and_then(OsStr::to_str)
        .filter(|name| !name.is_empty())
        .unwrap_or("dbcrust")
        .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_scheme_candidates_cover_every_url_scheme() {
        let values: Vec<String> = scheme_candidates().into_iter().map(|c| c.value).collect();
        for scheme in UrlScheme::iter() {
            assert!(values.contains(&scheme.url_prefix()), "{scheme}");
        }
        assert!(values.contains(&"postgres://".to_string()));
        assert!(values.contains(&"docker://".to_string()));
        assert!(values.contains(&"session://".to_string()));
    }

    #[test]
    fn test_bare_prefix_offers_schemes_and_compatible_files() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("data.csv"), "a,b\n").unwrap();
        std::fs::write(dir.path().join("notes.txt"), "").unwrap();
        std::fs::write(dir.path().join(".hidden.csv"), "").unwrap();
        std::fs::create_dir(dir.path().join("sub")).unwrap();

        let typed = format!("{}/", dir.path().display());
        let values: Vec<String> = url_candidates(&typed)
            .into_iter()
            .map(|c| c.value)
            .collect();
        assert!(values.contains(&format!("{typed}data.csv")), "{values:?}");
        assert!(values.contains(&format!("{typed}sub/")), "{values:?}");
        assert!(
            !values.iter().any(|v| v.ends_with("notes.txt")),
            "{values:?}"
        );
        assert!(
            !values.iter().any(|v| v.ends_with(".hidden.csv")),
            "{values:?}"
        );
        // Schemes are always offered for a bare word (the caller filters by prefix)
        assert!(values.contains(&"postgres://".to_string()));

        let values: Vec<String> = url_candidates(&format!("sqlite://{typed}"))
            .into_iter()
            .map(|c| c.value)
            .collect();
        assert!(
            values.contains(&format!("sqlite://{typed}sub/")),
            "{values:?}"
        );
        assert!(!values.contains(&"postgres://".to_string()));
    }

    #[test]
    fn test_network_schemes_get_no_candidates() {
        assert!(url_candidates("postgres://localhost/").is_empty());
        assert!(url_candidates("docker://name/db").is_empty());
        // A flag-like word still lists schemes (the parser only asks the
        // completer for argument positions), just no filesystem walk
        assert!(
            url_candidates("--for")
                .iter()
                .all(|c| c.value.ends_with("://"))
        );
    }

    #[test]
    fn test_bash_script_gets_colon_fix_and_calls_binary_back() {
        let script = completion_script(Shell::Bash, "dbcrust");
        assert!(script.contains("'dbcrust' __complete_word__"));
        assert!(script.contains("__usage_colon_prefix"));
        assert!(script.contains("complete -F _usage_complete_dbcrust 'dbcrust'"));

        let script = completion_script(Shell::Bash, "dbc");
        assert!(script.contains("'dbc' __complete_word__"));
        assert!(script.contains("__usage_colon_prefix"));
    }

    #[test]
    fn test_other_shells_are_passed_through() {
        for shell in [Shell::Zsh, Shell::Fish, Shell::PowerShell, Shell::Nu] {
            let script = completion_script(shell, "dbcrust");
            assert!(script.contains("__complete_word__"), "{shell:?}");
            assert!(!script.contains("__usage_colon_prefix"), "{shell:?}");
        }
    }

    #[test]
    fn test_binary_name_from_argv0() {
        assert_eq!(
            binary_name_from_argv0(Some(OsStr::new("/usr/bin/dbc"))),
            "dbc"
        );
        assert_eq!(
            binary_name_from_argv0(Some(OsStr::new("dbcrust"))),
            "dbcrust"
        );
        assert_eq!(binary_name_from_argv0(Some(OsStr::new(""))), "dbcrust");
        assert_eq!(binary_name_from_argv0(None), "dbcrust");
    }
}
