name: "Publish to PyPI"

on:
  workflow_call:
    inputs:
      plan:
        required: true
        type: string

jobs:
  pypi-publish-dbcrust:
    name: Upload dbcrust to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: "Install uv"
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: false

      - uses: actions/download-artifact@v4
        with:
          pattern: wheels_dbcrust-*
          path: wheels_dbcrust
          merge-multiple: true

      - name: "List downloaded artifacts"
        run: find wheels_dbcrust -type f -name "*.whl" | head -20

      - name: "Publish to TestPyPI"
        run: uv publish wheels_dbcrust/*
