name: "Publish to PyPI"

on:
  workflow_call:
    inputs:
      plan:
        required: true
        type: string

jobs:
  pypi-publish-dbcrust:
    name: Upload dbcrust to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: pypi
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: wheels_dbcrust-*
          path: wheels_dbcrust
          merge-multiple: true

      - name: "List downloaded artifacts"
        run: find wheels_dbcrust -type f -name "*.whl" | head -20

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: wheels_dbcrust/
